// Card catalog — seeded from issuer public terms (checked July 31, 2026).
// Each card has categories: array of {key, label, rate, unit: 'x'|'%', note?, cap?}
// `keywords` are used for fuzzy matching against the free-text query.
// `base` is the fallback/everything-else rate for that card.
// STARTER_CARD_IDS: cards that populate a brand-new wallet by default.
// Everything else in CARD_CATALOG is available to add via the settings sheet.

const STARTER_CARD_IDS = ['csp', 'amex-gold', 'hilton-aspire', 'bce', 'cfu', 'boa-ccr', 'nfcu', 'fidelity-visa', 'apple-card'];

const CARD_CATALOG = [
  {
    id: 'csp',
    name: 'Chase Sapphire Preferred',
    short: 'CSP',
    network: 'Visa',
    issuer: 'Chase',
    color: '#0f3fae',
    unit: 'x',
    pointValue: 1.0, // cents per point, cash-out value
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'chase-travel', rate: 5, label: 'Travel via Chase Travel', keywords: ['chase travel', 'flight booked through chase', 'hotel booked through chase'] },
      { key: 'dining', rate: 3, label: 'Dining, takeout & delivery', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'coffee', 'cafe', 'bar', 'brewery', 'starbucks'] },
      { key: 'gas-ev', rate: 3, label: 'Gas & EV charging', keywords: ['gas', 'gas station', 'fuel', 'ev charging', 'chargepoint', 'electric vehicle charging'] },
      { key: 'streaming', rate: 3, label: 'Select streaming services', keywords: ['netflix', 'hulu', 'disney+', 'disney plus', 'espn+', 'spotify', 'apple music', 'apple tv', 'streaming'] },
      { key: 'online-grocery', rate: 3, label: 'Online groceries (excl. Target/Walmart/wholesale)', keywords: ['instacart', 'online grocery', 'grocery delivery'] },
      { key: 'vacation-rental', rate: 3, label: 'Vacation homes (Airbnb, Vrbo)', keywords: ['airbnb', 'vrbo', 'vacation rental', 'vacation home'] },
      { key: 'other-travel', rate: 2, label: 'Other travel (airfare, hotel, rideshare, etc.)', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'spirit airlines', 'alaska airlines', 'hotel', 'motel', 'rideshare', 'uber ride', 'lyft', 'taxi', 'train', 'amtrak', 'parking', 'rental car', 'car rental', 'cruise', 'travel'] },
    ],
    notes: 'Points worth 1¢ cash back, up to ~1.5–1.25x via Chase Travel portal, more via airline/hotel transfer partners.',
  },
  {
    id: 'amex-gold',
    name: 'Amex Gold',
    short: 'Gold',
    network: 'Amex',
    issuer: 'American Express',
    color: '#caa04c',
    unit: 'x',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'dining', rate: 4, label: 'Restaurants worldwide (+takeout/delivery in US)', cap: '$50,000/yr', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'bar', 'brewery'] },
      { key: 'grocery', rate: 4, label: 'U.S. supermarkets', cap: '$25,000/yr', keywords: ['grocery', 'groceries', 'supermarket', 'whole foods', 'trader joe', 'stop & shop', 'stop and shop', 'shaws'] },
      { key: 'hotel', rate: 5, label: 'Prepaid hotels via Amex Travel', keywords: ['amex travel hotel', 'prepaid hotel'] },
      { key: 'flight', rate: 3, label: 'Flights (direct or Amex Travel)', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'spirit airlines', 'alaska airlines'] },
      { key: 'car-cruise', rate: 2, label: 'Prepaid car rentals / cruises via Amex Travel', keywords: ['cruise'] },
    ],
    notes: '4x dining/groceries is the strongest of any card in the wallet — default to this for food spend.',
  },
  {
    id: 'hilton-aspire',
    name: 'Amex Hilton Honors Aspire',
    short: 'Hilton Aspire',
    network: 'Amex',
    issuer: 'American Express',
    color: '#5b3a99',
    unit: 'x',
    pointValue: 0.5, // Hilton points redeem around 0.5¢/pt for standard rooms
    base: { rate: 3, label: 'Everything else' },
    categories: [
      { key: 'hilton', rate: 14, label: 'Hilton hotels & resorts (direct)', keywords: ['hilton', 'hampton inn', 'doubletree', 'embassy suites', 'waldorf astoria', 'conrad hotel', 'homewood suites', 'tru by hilton', 'canopy'] },
      { key: 'flight-direct', rate: 7, label: 'Flights (direct with airline or AmexTravel.com)', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'spirit airlines', 'alaska airlines'] },
      { key: 'car-rental', rate: 7, label: 'Car rentals (direct with select companies)', keywords: ['car rental', 'rental car', 'hertz', 'avis', 'enterprise rent'] },
      { key: 'dining', rate: 7, label: 'U.S. restaurants (incl. takeout/delivery)', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'bar', 'brewery', 'coffee', 'cafe', 'starbucks'] },
    ],
    notes: 'Best card in the wallet for any Hilton stay — 14x plus Diamond status perks. $550 annual fee already sunk, so lean on it for travel/dining too.',
  },
  {
    id: 'bce',
    name: 'Amex Blue Cash Everyday',
    short: 'Blue Cash Everyday',
    network: 'Amex',
    issuer: 'American Express',
    color: '#1f6fb2',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'grocery', rate: 3, label: 'U.S. supermarkets', cap: '$6,000/yr', keywords: ['grocery', 'groceries', 'supermarket', 'whole foods', 'trader joe', 'stop & shop', 'stop and shop', 'shaws'] },
      { key: 'gas', rate: 3, label: 'U.S. gas stations', cap: '$6,000/yr', keywords: ['gas', 'gas station', 'fuel', 'exxon', 'mobil', 'shell', 'chevron', 'bp', 'sunoco'] },
      { key: 'online-retail', rate: 3, label: 'U.S. online retail', cap: '$6,000/yr', keywords: ['amazon', 'online shopping', 'online retail', 'ebay', 'etsy', 'online order', 'website purchase', 'target.com', 'walmart.com'] },
    ],
    notes: 'Best backup for Amazon/online retail since it has no annual fee and stacks with Amex Offers.',
  },
  {
    id: 'cfu',
    name: 'Chase Freedom Unlimited',
    short: 'CFU',
    network: 'Visa',
    issuer: 'Chase',
    color: '#0a5ec9',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1.5, label: 'Everything else' },
    categories: [
      { key: 'chase-travel', rate: 5, label: 'Travel via Chase Travel', keywords: ['chase travel', 'flight booked through chase', 'hotel booked through chase'] },
      { key: 'dining', rate: 3, label: 'Dining, incl. takeout & delivery', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'bar', 'coffee', 'cafe', 'starbucks'] },
      { key: 'drugstore', rate: 3, label: 'Drugstores', keywords: ['cvs', 'walgreens', 'rite aid', 'drugstore', 'pharmacy'] },
    ],
    notes: 'Reliable 1.5% floor beats most cards\' base rate — good default when nothing else applies.',
  },
  {
    id: 'boa-ccr',
    name: 'Bank of America Customized Cash Rewards',
    short: 'BofA CCR',
    network: 'Visa/Mastercard',
    issuer: 'Bank of America',
    color: '#c8102e',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    editableChoiceCategory: true, // 3% category is user-selectable
    choiceCategoryOptions: ['online-shopping', 'gas-ev', 'dining', 'travel', 'drugstore', 'home-improvement'],
    choiceCategory: 'online-shopping', // default selection — user can change in settings
    categoryDefinitions: {
      'online-shopping': { label: 'Online shopping (incl. streaming, cable, phone)', keywords: ['amazon', 'online shopping', 'online retail', 'ebay', 'etsy', 'online order', 'streaming', 'netflix', 'hulu', 'phone bill', 'cable bill', 'internet bill', 'target.com', 'walmart.com'] },
      'gas-ev': { label: 'Gas & EV charging', keywords: ['gas', 'gas station', 'fuel', 'ev charging', 'chargepoint'] },
      'dining': { label: 'Dining', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'takeout', 'doordash', 'ubereats', 'grubhub', 'bar', 'coffee', 'cafe'] },
      'travel': { label: 'Travel', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'hotel', 'rideshare', 'uber ride', 'lyft', 'taxi', 'train', 'parking', 'rental car', 'travel'] },
      'drugstore': { label: 'Drug stores & pharmacy', keywords: ['cvs', 'walgreens', 'rite aid', 'drugstore', 'pharmacy'] },
      'home-improvement': { label: 'Home improvement & furnishings', keywords: ['home depot', 'lowes', 'furniture', 'ikea', 'wayfair', 'hardware store', 'home improvement'] },
    },
    grocery: { rate: 2, label: 'Grocery stores & wholesale clubs', keywords: ['grocery', 'groceries', 'supermarket', 'whole foods', 'trader joe', 'costco', 'bjs', "bj's", 'sams club', "sam's club", 'wholesale club', 'stop & shop', 'stop and shop', 'shaws'] },
    choiceRate: 3,
    cap: '$2,500/quarter combined (choice + grocery)',
    notes: 'Choice category can be changed once a month in the BofA app — edit it here to match. 2% grocery/wholesale club is automatic regardless of choice.',
  },
  {
    id: 'nfcu',
    name: 'Navy Federal cashRewards',
    short: 'NFCU',
    network: 'Visa',
    issuer: 'Navy Federal Credit Union',
    color: '#003b5c',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1.5, label: 'Everything, no categories' },
    categories: [],
    notes: 'Flat rate, no categories to track. Assumes standard cashRewards (1.5%) — bump to 2% below if you have cashRewards Plus.',
  },
  {
    id: 'fidelity-visa',
    name: 'Fidelity Rewards Visa Signature',
    short: 'Fidelity Visa',
    network: 'Visa',
    issuer: 'Fidelity (Elan Financial)',
    color: '#0a8a4a',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 2, label: 'Everything, no categories (when redeemed to Fidelity account)' },
    categories: [],
    notes: 'Flat 2% on everything, deposited straight into your Fidelity account — perfect for subscriptions & Roth funding. Only earns 2% if redeemed into an eligible Fidelity account (1% otherwise).',
  },
  {
    id: 'apple-card',
    name: 'Apple Card',
    short: 'Apple Card',
    network: 'Mastercard',
    issuer: 'Apple (Goldman Sachs)',
    color: '#3a3a3c',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Physical card swipe (Apple Pay not used)' },
    categories: [
      { key: 'apple', rate: 3, label: 'Apple purchases (Apple Store, apple.com, App Store)', keywords: ['apple store', 'iphone', 'ipad', 'macbook', 'mac', 'apple watch', 'airpods', 'app store', 'apple music', 'apple tv', 'icloud', 'apple purchase'] },
      { key: 'partner-3', rate: 3, label: 'Partner merchants via Apple Pay (Ace Hardware, Uber, Walgreens, Nike, Exxon/Mobil, Panera, T-Mobile, Duane Reade, Booking.com, Hertz)', keywords: ['ace hardware', 'uber ride', 'uber eats', 'walgreens', 'nike', 'exxon', 'mobil', 'panera', 't-mobile', 'duane reade', 'booking.com', 'hertz'] },
      { key: 'apple-pay-other', rate: 2, label: 'Any other purchase paid via Apple Pay', keywords: [] },
    ],
    notes: 'Only earns the listed rate when paid with Apple Pay — physical card taps/swipes drop to 1%. This tool assumes Apple Pay is used unless it is a partner-3% merchant paid by physical card.',
  },
  {
    id: 'robinhood-gold-card',
    name: 'Robinhood Gold Card',
    short: 'Robinhood Gold',
    network: 'Visa',
    issuer: 'Robinhood',
    color: '#00c805',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 3, label: 'All purchases' },
    categories: [
      { key: 'travel-portal', rate: 5, label: 'Travel booked through the Robinhood Travel Portal', keywords: ['robinhood travel', 'robinhood travel portal'] },
    ],
    notes: 'Flat 3% cash back on everything (1 point = 1\u00a2 when redeemed as cash back to a Robinhood brokerage/spending account), plus 5% on travel booked via the Robinhood Travel Portal. No card annual fee, but requires an active Robinhood Gold subscription ($50/year) \u2014 factor that into the effective return. Cash-back redemption requires a Robinhood Financial brokerage account; other redemption options (gift cards, statement credit, merchandise) can be worth less than 1\u00a2/point.',
  },
  {
    id: 'citi-double-cash',
    name: 'Citi Double Cash',
    short: 'Double Cash',
    network: 'Mastercard',
    issuer: 'Citi',
    color: '#1a4f9c',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 2, label: 'Everything, no categories (1% on purchase + 1% on payment)' },
    categories: [],
    notes: 'Flat 2% on everything — no annual fee, no categories to track. Great default/backup card.',
  },
  {
    id: 'citi-custom-cash',
    name: 'Citi Custom Cash',
    short: 'Custom Cash',
    network: 'Mastercard',
    issuer: 'Citi',
    color: '#0f7a5c',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'top-category', rate: 5, label: 'Your top eligible spend category this billing cycle', cap: '$500/month combined', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'gas', 'gas station', 'fuel', 'grocery', 'groceries', 'supermarket', 'whole foods', 'streaming', 'netflix', 'hulu', 'drugstore', 'cvs', 'walgreens', 'home depot', 'lowes', 'home improvement', 'gym', 'fitness club', 'concert', 'ticketmaster', 'live entertainment', 'transit', 'train', 'bus', 'toll'] },
    ],
    notes: 'Automatically applies 5% to whichever eligible category you spend most in that billing cycle (restaurants, gas, grocery, select travel/transit, streaming, drugstores, home improvement, fitness, live entertainment) — capped at $500/month. Closed to new applicants as of May 2026, but still valid if you already have one.',
  },
  {
    id: 'discover-it-cash-back',
    name: 'Discover it Cash Back',
    short: 'Discover it',
    network: 'Discover',
    issuer: 'Discover',
    color: '#e57200',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    editableChoiceCategory: true,
    choiceCategoryOptions: ['grocery-wholesale', 'restaurants-home-improvement', 'gas-transit-drugstore', 'amazon-drugstore'],
    choiceCategory: 'gas-transit-drugstore',
    categoryDefinitions: {
      'grocery-wholesale': { label: 'Grocery stores, wholesale clubs & streaming (Q1-style)', keywords: ['grocery', 'groceries', 'supermarket', 'whole foods', 'costco', 'bjs', "bj's", 'sams club', "sam's club", 'streaming', 'netflix'] },
      'restaurants-home-improvement': { label: 'Restaurants & home improvement (Q2-style)', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'home depot', 'lowes', 'home improvement'] },
      'gas-transit-drugstore': { label: 'Gas, transportation & drugstores (Q3-style)', keywords: ['gas', 'gas station', 'fuel', 'transit', 'train', 'bus', 'uber ride', 'lyft', 'cvs', 'walgreens', 'drugstore'] },
      'amazon-drugstore': { label: 'Amazon.com & drugstores (Q4-style)', keywords: ['amazon', 'online order', 'cvs', 'walgreens', 'drugstore'] },
    },
    choiceRate: 5,
    cap: '$1,500/quarter (must activate)',
    notes: 'Rotating 5% categories change every quarter and require activation — pick whichever is currently active in your Discover account. Falls back to 1% outside the active category or once you hit the $1,500 quarterly cap.',
  },
  {
    id: 'venture-x',
    name: 'Capital One Venture X',
    short: 'Venture X',
    network: 'Visa',
    issuer: 'Capital One',
    color: '#004977',
    unit: 'x',
    pointValue: 1.0,
    base: { rate: 2, label: 'Everything else' },
    categories: [
      { key: 'c1-hotel-car', rate: 10, label: 'Hotels & rental cars via Capital One Travel', keywords: ['capital one travel hotel', 'capital one travel car'] },
      { key: 'c1-flight-vacation', rate: 5, label: 'Flights & vacation rentals via Capital One Travel', keywords: ['capital one travel flight', 'capital one travel vacation rental'] },
      { key: 'c1-entertainment', rate: 5, label: 'Capital One Entertainment purchases', keywords: ['capital one entertainment', 'ticketmaster capital one'] },
    ],
    notes: 'Unlimited 2x miles on every purchase with no categories to track — strong everyday flat-rate card once you clear the $395 fee via travel credits.',
  },
  {
    id: 'savorone',
    name: 'Capital One SavorOne',
    short: 'SavorOne',
    network: 'Mastercard',
    issuer: 'Capital One',
    color: '#8a1538',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'dining', rate: 3, label: 'Dining', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'bar', 'brewery', 'coffee', 'cafe', 'starbucks'] },
      { key: 'entertainment', rate: 3, label: 'Entertainment', keywords: ['movie', 'movie theater', 'concert', 'ticketmaster', 'live entertainment', 'amusement park', 'bowling'] },
      { key: 'streaming', rate: 3, label: 'Popular streaming services', keywords: ['netflix', 'hulu', 'disney+', 'disney plus', 'spotify', 'apple music', 'apple tv', 'streaming'] },
      { key: 'grocery', rate: 3, label: 'Grocery stores (excl. Walmart/Target/superstores)', keywords: ['grocery', 'groceries', 'supermarket', 'whole foods', 'trader joe', 'stop & shop', 'stop and shop', 'shaws'] },
    ],
    notes: 'No annual fee, strong 3% across dining/entertainment/streaming/grocery — solid everyday lifestyle card.',
  },
  {
    id: 'quicksilver',
    name: 'Capital One Quicksilver',
    short: 'Quicksilver',
    network: 'Mastercard',
    issuer: 'Capital One',
    color: '#565a5c',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1.5, label: 'Everything, no categories' },
    categories: [],
    notes: 'Flat 1.5% on everything — no annual fee, no categories. Simple backup/default card.',
  },
  {
    id: 'wf-active-cash',
    name: 'Wells Fargo Active Cash',
    short: 'Active Cash',
    network: 'Visa',
    issuer: 'Wells Fargo',
    color: '#d71e28',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 2, label: 'Everything, no categories' },
    categories: [],
    notes: 'Flat 2% on everything — no annual fee, no categories to track.',
  },
  {
    id: 'amex-platinum',
    name: 'Amex Platinum',
    short: 'Platinum',
    network: 'Amex',
    issuer: 'American Express',
    color: '#8f8f8f',
    unit: 'x',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'flight', rate: 5, label: 'Flights booked direct with airline or Amex Travel', cap: '$500,000/yr', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'spirit airlines', 'alaska airlines'] },
      { key: 'hotel', rate: 5, label: 'Prepaid hotels booked via Amex Travel', keywords: ['amex travel hotel', 'prepaid hotel'] },
    ],
    notes: 'Premium travel card — 5x on flights/prepaid hotels is strong, but 1x elsewhere means it rarely wins outside travel spend. $895 annual fee offset mainly by travel credits/lounge access, not everyday cash back.',
  },
  {
    id: 'amex-bcp',
    name: 'Amex Blue Cash Preferred',
    short: 'Blue Cash Preferred',
    network: 'Amex',
    issuer: 'American Express',
    color: '#1f6fb2',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'grocery', rate: 6, label: 'U.S. supermarkets', cap: '$6,000/yr', keywords: ['grocery', 'groceries', 'supermarket', 'whole foods', 'trader joe', 'stop & shop', 'stop and shop', 'shaws'] },
      { key: 'streaming', rate: 6, label: 'Select U.S. streaming subscriptions', keywords: ['netflix', 'hulu', 'disney+', 'disney plus', 'spotify', 'apple music', 'apple tv', 'hbo max', 'peacock', 'youtube premium', 'youtube tv', 'streaming'] },
      { key: 'gas-transit', rate: 3, label: 'U.S. gas stations & transit', keywords: ['gas', 'gas station', 'fuel', 'exxon', 'mobil', 'shell', 'chevron', 'transit', 'train', 'bus', 'toll', 'parking', 'uber ride', 'lyft', 'taxi'] },
    ],
    notes: 'Best-in-class 6% grocery card up to $6,000/yr, plus 6% streaming. $95 annual fee ($0 first year) — easily worth it for a household that spends on groceries.',
  },
  {
    id: 'csr',
    name: 'Chase Sapphire Reserve',
    short: 'CSR',
    network: 'Visa',
    issuer: 'Chase',
    color: '#03203d',
    unit: 'x',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'chase-travel', rate: 8, label: 'All purchases via Chase Travel (incl. The Edit)', keywords: ['chase travel', 'flight booked through chase', 'hotel booked through chase', 'the edit'] },
      { key: 'flight-hotel-direct', rate: 4, label: 'Flights & hotels booked directly', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'spirit airlines', 'alaska airlines', 'hotel', 'motel'] },
      { key: 'dining', rate: 3, label: 'Dining worldwide (incl. takeout & delivery)', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'coffee', 'cafe', 'bar', 'brewery', 'starbucks'] },
    ],
    notes: 'Premium travel card with a $795 annual fee offset by travel/dining credits. Strongest when booking through the Chase Travel portal (8x) or dining out (3x).',
  },
  {
    id: 'freedom-flex',
    name: 'Chase Freedom Flex',
    short: 'Freedom Flex',
    network: 'Mastercard',
    issuer: 'Chase',
    color: '#0a5ec9',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    editableChoiceCategory: true,
    choiceCategoryOptions: ['grocery-gas', 'home-improvement-gym', 'gas-transit', 'amazon-target'],
    choiceCategory: 'gas-transit',
    categoryDefinitions: {
      'grocery-gas': { label: 'Grocery stores & gas stations (Q1-style)', keywords: ['grocery', 'groceries', 'supermarket', 'whole foods', 'gas', 'gas station', 'fuel'] },
      'home-improvement-gym': { label: 'Home improvement & gyms (Q2-style)', keywords: ['home depot', 'lowes', 'home improvement', 'gym', 'fitness club'] },
      'gas-transit': { label: 'Gas stations & select online merchants (Q3-style)', keywords: ['gas', 'gas station', 'fuel', 'online order', 'online shopping'] },
      'amazon-target': { label: 'Amazon.com & PayPal (Q4-style)', keywords: ['amazon', 'paypal', 'online order'] },
    },
    choiceRate: 5,
    cap: '$1,500/quarter (must activate)',
    always: [
      { key: 'chase-travel', rate: 5, label: 'Travel via Chase Travel', keywords: ['chase travel', 'flight booked through chase', 'hotel booked through chase'] },
      { key: 'dining', rate: 3, label: 'Dining, incl. takeout & delivery', keywords: ['restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'bar', 'coffee', 'cafe', 'starbucks'] },
      { key: 'drugstore', rate: 3, label: 'Drugstores', keywords: ['cvs', 'walgreens', 'rite aid', 'drugstore', 'pharmacy'] },
    ],
    notes: 'Rotating 5% categories require quarterly activation, capped at $1,500/quarter — plus permanent 5% Chase Travel, 3% dining, 3% drugstores.',
  },
  {
    id: 'us-bank-cash-plus',
    name: 'US Bank Cash+',
    short: 'Cash+',
    network: 'Visa',
    issuer: 'US Bank',
    color: '#003366',
    unit: '%',
    pointValue: 1.0,
    base: { rate: 1, label: 'Everything else' },
    editableChoiceCategory: true,
    choiceCategoryOptions: ['streaming-utilities', 'electronics-furniture', 'fitness-clothing', 'department-sporting'],
    choiceCategory: 'streaming-utilities',
    categoryDefinitions: {
      'streaming-utilities': { label: 'TV/internet/streaming & home utilities', keywords: ['netflix', 'hulu', 'streaming', 'internet bill', 'cable bill', 'utility bill', 'electric bill', 'phone bill', 'cell phone'] },
      'electronics-furniture': { label: 'Electronics & furniture stores', keywords: ['best buy', 'electronics', 'furniture', 'ikea', 'wayfair'] },
      'fitness-clothing': { label: 'Gyms & select clothing stores', keywords: ['gym', 'fitness club', 'clothing store', 'apparel'] },
      'department-sporting': { label: 'Department & sporting goods stores', keywords: ['department store', 'sporting goods', 'dicks sporting goods'] },
    },
    grocery: { rate: 2, label: 'Your chosen everyday category (gas, dining, or grocery)', keywords: ['gas', 'gas station', 'fuel', 'restaurant', 'dining', 'dinner', 'lunch', 'grocery', 'groceries', 'supermarket', 'whole foods'] },
    choiceRate: 5,
    cap: '$2,000/quarter combined (two 5% categories, must enroll)',
    notes: 'Pick two 5% categories and one 2% everyday category each quarter — flexible but requires quarterly enrollment or it defaults to 1% everywhere.',
  },
  {
    id: 'ink-preferred',
    name: 'Chase Ink Business Preferred',
    short: 'Ink Preferred',
    network: 'Visa',
    issuer: 'Chase',
    color: '#0f3fae',
    unit: 'x',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'travel', rate: 3, label: 'Travel (airfare, hotels, rental cars, trains, taxis)', cap: '$150,000/yr combined w/ shipping, internet/cable/phone & ads', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'spirit airlines', 'alaska airlines', 'hotel', 'motel', 'rideshare', 'uber ride', 'lyft', 'taxi', 'train', 'amtrak', 'rental car', 'car rental', 'cruise', 'travel'] },
      { key: 'shipping', rate: 3, label: 'Shipping purchases', cap: '$150,000/yr combined', keywords: ['ups', 'fedex', 'usps', 'dhl', 'shipping', 'postage', 'courier', 'mailbox store'] },
      { key: 'internet-cable-phone', rate: 3, label: 'Internet, cable & phone services', cap: '$150,000/yr combined', keywords: ['internet bill', 'cable bill', 'phone bill', 'cell phone bill', 'wireless bill', 'landline'] },
      { key: 'advertising', rate: 3, label: 'Advertising on social media & search engines', cap: '$150,000/yr combined', keywords: ['google ads', 'facebook ads', 'meta ads', 'instagram ads', 'linkedin ads', 'bing ads', 'tiktok ads', 'social media advertising', 'search engine advertising'] },
    ],
    notes: 'Business version of Sapphire Preferred. $95 annual fee. 3x on travel/shipping/internet-cable-phone/advertising share one $150,000/yr combined cap, then 1x. Points pool with a personal Sapphire card for transfer partners.',
  },
  {
    id: 'ink-cash',
    name: 'Chase Ink Business Cash',
    short: 'Ink Cash',
    network: 'Visa',
    issuer: 'Chase',
    color: '#0a5ec9',
    unit: '%',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 1, label: 'Everything, no cap' },
    categories: [
      { key: 'office-internet', rate: 5, label: 'Office supply stores & internet/cable/phone services', cap: '$25,000/yr combined', keywords: ['office depot', 'staples', 'office supply', 'internet bill', 'cable bill', 'phone bill', 'cell phone bill', 'wireless bill'] },
      { key: 'gas-dining', rate: 2, label: 'Gas stations & restaurants', cap: '$25,000/yr combined', keywords: ['gas', 'gas station', 'fuel', 'restaurant', 'dining', 'dinner', 'lunch', 'breakfast', 'takeout', 'doordash', 'ubereats', 'uber eats', 'grubhub', 'food delivery', 'bar', 'coffee', 'cafe', 'starbucks'] },
    ],
    notes: 'No annual fee. 5% office supplies/internet/cable/phone and 2% gas/dining each capped at $25,000/yr combined spend, then drops to 1%.',
  },
  {
    id: 'ink-unlimited',
    name: 'Chase Ink Business Unlimited',
    short: 'Ink Unlimited',
    network: 'Visa',
    issuer: 'Chase',
    color: '#0a5ec9',
    unit: '%',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 1.5, label: 'Everything, no categories' },
    categories: [],
    notes: 'No annual fee. Flat unlimited 1.5% cash back on every purchase — no categories or caps.',
  },
  {
    id: 'amex-business-gold',
    name: 'Amex Business Gold',
    short: 'Biz Gold',
    network: 'Amex',
    issuer: 'American Express',
    color: '#caa04c',
    unit: 'x',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'top2-flex', rate: 4, label: 'Your top 2 spend categories this billing cycle (ads, electronics/software, restaurants, gas, transit, wireless)', cap: '$150,000/yr combined', keywords: ['google ads', 'facebook ads', 'meta ads', 'advertising', 'electronics', 'software', 'cloud', 'saas', 'restaurant', 'dining', 'dinner', 'lunch', 'takeout', 'doordash', 'gas', 'gas station', 'fuel', 'transit', 'train', 'bus', 'toll', 'parking', 'uber ride', 'lyft', 'taxi', 'wireless bill', 'cell phone bill', 'phone bill'] },
      { key: 'flight-hotel', rate: 3, label: 'Flights & prepaid hotels via Amex Travel', keywords: ['flight', 'airfare', 'airline', 'airline ticket', 'plane ticket', 'book a flight', 'delta', 'united', 'american airlines', 'southwest', 'jetblue', 'spirit airlines', 'alaska airlines', 'amex travel hotel', 'prepaid hotel'] },
    ],
    notes: '$375 annual fee. Automatically applies 4x to your top 2 of 6 eligible categories each billing cycle (up to $150,000/yr combined), so actual category depends on that cycle\'s spend mix — assume it matches if the item fits one of the 6.',
  },
  {
    id: 'amex-business-platinum',
    name: 'Amex Business Platinum',
    short: 'Biz Platinum',
    network: 'Amex',
    issuer: 'American Express',
    color: '#8f8f8f',
    unit: 'x',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 1, label: 'Everything else' },
    categories: [
      { key: 'flight-hotel', rate: 5, label: 'Flights & prepaid hotels via Amex Travel', keywords: ['amex travel hotel', 'prepaid hotel', 'flight booked through amex', 'amextravel'] },
      { key: 'key-business', rate: 2, label: 'Key business purchases $5,000+ or select categories', cap: '$2,000,000/yr', keywords: ['large purchase', 'bulk purchase', 'wholesale order', 'equipment purchase'] },
    ],
    notes: '$895 annual fee. 5x on flights/prepaid hotels booked via Amex Travel, 2x on purchases of $5,000+ or select business categories (up to $2M/yr), 1x elsewhere. Value comes mainly from travel credits/lounge access, not everyday spend.',
  },
  {
    id: 'amex-blue-business-cash',
    name: 'Amex Blue Business Cash',
    short: 'Blue Biz Cash',
    network: 'Amex',
    issuer: 'American Express',
    color: '#1f6fb2',
    unit: '%',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 1, label: 'Everything after $50,000/yr cap' },
    categories: [
      { key: 'flat', rate: 2, label: 'All eligible purchases', cap: '$50,000/yr', keywords: [] },
    ],
    notes: 'No annual fee. Flat 2% cash back on all purchases up to $50,000/yr combined, then 1%. Simplest business cash-back option — no categories to track.',
  },
  {
    id: 'amex-blue-business-plus',
    name: 'Amex Blue Business Plus',
    short: 'Blue Biz Plus',
    network: 'Amex',
    issuer: 'American Express',
    color: '#1f6fb2',
    unit: 'x',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 1, label: 'Everything after $50,000/yr cap' },
    categories: [
      { key: 'flat', rate: 2, label: 'All eligible purchases', cap: '$50,000/yr', keywords: [] },
    ],
    notes: 'No annual fee. Flat 2x Membership Rewards points on all purchases up to $50,000/yr combined, then 1x. Points transfer to airline/hotel partners, unlike the Blue Business Cash.',
  },
  {
    id: 'venture-x-business',
    name: 'Capital One Venture X Business',
    short: 'Venture X Biz',
    network: 'Visa',
    issuer: 'Capital One',
    color: '#004977',
    unit: 'x',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 2, label: 'Everything else' },
    categories: [
      { key: 'c1-hotel-car', rate: 10, label: 'Hotels & rental cars via Capital One Business Travel', keywords: ['capital one business travel hotel', 'capital one business travel car'] },
      { key: 'c1-flight-vacation', rate: 5, label: 'Flights & vacation rentals via Capital One Business Travel', keywords: ['capital one business travel flight', 'capital one business travel vacation rental'] },
    ],
    notes: '$395 annual fee. Unlimited 2x miles on every purchase, no categories to track — business twin of the personal Venture X. Fee mostly offset by $300 annual travel credit + 10,000 anniversary miles.',
  },
  {
    id: 'spark-cash-plus',
    name: 'Capital One Spark Cash Plus',
    short: 'Spark Cash+',
    network: 'Visa',
    issuer: 'Capital One',
    color: '#565a5c',
    unit: '%',
    pointValue: 1.0,
    businessCard: true,
    base: { rate: 2, label: 'Everything, no categories' },
    categories: [
      { key: 'c1-hotel-car', rate: 5, label: 'Hotels & rental cars via Capital One Business Travel', keywords: ['capital one business travel hotel', 'capital one business travel car'] },
    ],
    notes: '$150 annual fee (refunded if you spend $150,000+/yr). Flat unlimited 2% cash back on everything, plus 5% on hotels/rental cars via Capital One Business Travel. Charge card — must pay in full monthly.',
  },
];

// ---------- Cobranded cards (airline / hotel / retail) ----------
// Rates researched from official issuer pages, checked August 1, 2026.
const COBRAND_CARDS = [
  {
    id: "delta-skymiles-gold-amex",
    name: "Delta SkyMiles Gold American Express Card",
    short: "Delta Gold",
    network: "Amex",
    issuer: "American Express",
    color: "#a5122a",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1X miles per dollar on all other eligible purchases" },
    categories: [
      { key: "delta_purchases", rate: 2, label: "Delta purchases", keywords: ["delta flight", "book with delta", "delta.com", "delta vacations", "fly delta", "delta airlines ticket"] },
      { key: "dining", rate: 2, label: "Restaurants (incl. takeout/delivery in the U.S.)", keywords: ["restaurant", "dining", "takeout", "food delivery", "doordash", "uber eats", "grubhub"] },
      { key: "groceries", rate: 2, label: "U.S. supermarkets", keywords: ["grocery store", "supermarket", "whole foods", "kroger", "safeway", "trader joe's"] },
    ],
    notes: "Best low-fee entry-level Delta card: free first (and domestic second) checked bag, Zone 5 priority boarding, and 15% award redemption discount make it the pick for occasional Delta flyers who also want 2X on dining/groceries without a big annual fee.",
    cobranded: true,
  },
  {
    id: "delta-skymiles-platinum-amex",
    name: "Delta SkyMiles Platinum American Express Card",
    short: "Delta Platinum",
    network: "Amex",
    issuer: "American Express",
    color: "#7c1128",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1X miles per dollar on other eligible purchases" },
    categories: [
      { key: "delta_purchases", rate: 3, label: "Delta purchases", keywords: ["delta flight", "book with delta", "delta.com", "delta vacations", "fly delta", "delta airlines ticket"] },
      { key: "hotels", rate: 3, label: "Hotels booked directly with the hotel", keywords: ["hotel", "book direct hotel", "marriott.com", "hilton.com", "hyatt.com"] },
      { key: "dining", rate: 2, label: "Restaurants (incl. takeout/delivery in the U.S.)", keywords: ["restaurant", "dining", "takeout", "food delivery", "doordash", "uber eats", "grubhub"] },
      { key: "groceries", rate: 2, label: "U.S. supermarkets", keywords: ["grocery store", "supermarket", "whole foods", "kroger", "safeway", "trader joe's"] },
    ],
    notes: "Mid-tier Delta card adding a $120 rideshare credit, $150 Delta Stays credit, Resy dining credit, Global Entry/TSA PreCheck credit, and a companion certificate on renewal — good fit for frequent Delta flyers who also travel by hotel/rideshare and want the annual fee substantially offset by credits.",
    cobranded: true,
  },
  {
    id: "delta-skymiles-reserve-amex",
    name: "Delta SkyMiles Reserve American Express Card",
    short: "Delta Reserve",
    network: "Amex",
    issuer: "American Express",
    color: "#4a0e1c",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1X miles per dollar on other eligible purchases" },
    categories: [
      { key: "delta_purchases", rate: 3, label: "Delta purchases", keywords: ["delta flight", "book with delta", "delta.com", "delta vacations", "fly delta", "delta airlines ticket"] },
    ],
    notes: "Top-tier Delta card: Delta Sky Club access (15 visits/year, unlimited after $75K spend), Centurion Lounge access when flying Delta, companion certificate, $200 Delta Stays credit, and $2,500 MQD HeadStart — best for very frequent/premium Delta flyers who value lounge access over broad bonus categories.",
    cobranded: true,
  },
  {
    id: "united-explorer-chase",
    name: "United Explorer Card",
    short: "United Explorer",
    network: "Visa",
    issuer: "Chase",
    color: "#002244",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1X mile on all other purchases" },
    categories: [
      { key: "united_flights", rate: 9, label: "Eligible United flights (total, incl. MileagePlus base earning)", keywords: ["united flight", "book united airlines", "united.com", "fly united"] },
      { key: "united_purchases", rate: 3, label: "All other eligible United purchases (bags, upgrades, inflight, etc.)", keywords: ["united bag fee", "united seat upgrade", "united inflight purchase"] },
      { key: "hotels_direct", rate: 2, label: "Hotel stays booked directly with the hotel", keywords: ["hotel", "book direct hotel", "marriott.com", "hilton.com", "hyatt.com"] },
      { key: "dining", rate: 2, label: "Dining, including eligible delivery services", keywords: ["restaurant", "dining", "food delivery", "doordash", "uber eats", "grubhub"] },
    ],
    notes: "Moderate-fee United card standing out for two free United Club one-time lounge passes per year, free first checked bag for cardholder plus one companion, priority boarding, and a $120 Global Entry/TSA PreCheck credit — a strong pick for United flyers who want lounge access without a premium annual fee.",
    cobranded: true,
  },
  {
    id: "united-quest-chase",
    name: "United Quest Card",
    short: "United Quest",
    network: "Visa",
    issuer: "Chase",
    color: "#0033a0",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1X mile on all other purchases" },
    categories: [
      { key: "united_flights", rate: 10, label: "Eligible United flights (total, incl. MileagePlus base earning)", keywords: ["united flight", "book united airlines", "united.com", "fly united"] },
      { key: "united_purchases", rate: 4, label: "All other eligible United purchases", keywords: ["united bag fee", "united seat upgrade", "united inflight purchase"] },
      { key: "renowned_hotels", rate: 5, label: "Hotel stays prepaid through Renowned Hotels and Resorts for United Cardmembers", keywords: ["renowned hotels", "united hotel collection"] },
      { key: "travel_other", rate: 2, label: "Other travel (airfare, trains, transit, cruise, hotels, car rental, taxi, rideshare, tolls)", keywords: ["train ticket", "amtrak", "car rental", "taxi", "rideshare", "uber", "lyft", "toll", "cruise", "hotel"] },
      { key: "dining", rate: 2, label: "Dining, including eligible delivery services", keywords: ["restaurant", "dining", "food delivery", "doordash", "uber eats", "grubhub"] },
      { key: "streaming", rate: 2, label: "Select streaming services", keywords: ["netflix", "hulu", "disney+", "streaming subscription"] },
    ],
    notes: "Premium mid-tier United card with free first AND second checked bags for cardholder plus a companion, priority boarding, a $200 annual United travel credit, an annual 10,000-mile award flight discount, and PQP earning toward elite status — best for frequent United flyers pursuing status who check multiple bags.",
    cobranded: true,
  },
  {
    id: "southwest-rapid-rewards-plus",
    name: "Southwest Rapid Rewards Plus Card",
    short: "Southwest Plus",
    network: "Visa",
    issuer: "Chase",
    color: "#304cb2",
    unit: "x",
    pointValue: 1.4,
    base: { rate: 1, label: "1 point per dollar on all other purchases" },
    categories: [
      { key: "southwest_purchases", rate: 2, label: "Southwest Airlines purchases", keywords: ["southwest flight", "book southwest", "southwest.com", "fly southwest"] },
      { key: "gas_grocery", rate: 2, label: "Gas stations and grocery stores (combined)", cap: "First $5,000 in combined purchases per anniversary year", keywords: ["gas station", "fuel", "grocery store", "supermarket"] },
    ],
    notes: "Entry-level Southwest card: 3,000 anniversary points each year, 10,000 Companion Pass qualifying points boost annually, free first and second checked bags, and Group 5 boarding — good pick for occasional Southwest flyers wanting the lowest fee among the two personal Southwest cards.",
    cobranded: true,
  },
  {
    id: "southwest-rapid-rewards-premier",
    name: "Southwest Rapid Rewards Premier Card",
    short: "Southwest Premier",
    network: "Visa",
    issuer: "Chase",
    color: "#1a2f6e",
    unit: "x",
    pointValue: 1.4,
    base: { rate: 1, label: "1 point per dollar on all other purchases" },
    categories: [
      { key: "southwest_purchases", rate: 3, label: "Southwest Airlines purchases", keywords: ["southwest flight", "book southwest", "southwest.com", "fly southwest"] },
      { key: "grocery_dining", rate: 2, label: "Grocery stores and restaurants (combined)", cap: "First $8,000 in combined purchases per anniversary year", keywords: ["grocery store", "supermarket", "restaurant", "dining"] },
    ],
    notes: "Higher-tier Southwest personal card: 6,000 anniversary points each year, higher 3X on Southwest purchases, complimentary Preferred seat selection, 1,500 tier-qualifying points per $5,000 spent toward A-List status, and 10,000 Companion Pass qualifying points boost — best for more frequent Southwest flyers chasing A-List/Companion Pass.",
    cobranded: true,
  },
  {
    id: "jetblue-card",
    name: "JetBlue Card",
    short: "JetBlue Card",
    network: "Mastercard",
    issuer: "Barclays",
    color: "#00285e",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1X points on all other purchases" },
    categories: [
      { key: "jetblue_paisly", rate: 3, label: "Eligible JetBlue and Paisly purchases", keywords: ["jetblue flight", "book jetblue", "jetblue.com", "paisly", "fly jetblue"] },
      { key: "dining_grocery", rate: 2, label: "Restaurants and eligible grocery stores", keywords: ["restaurant", "dining", "grocery store", "supermarket"] },
    ],
    notes: "No-annual-fee JetBlue starter card; does not include a free checked bag or priority boarding (unlike the JetBlue Plus Card), so it's best purely for fee-free everyday earning by occasional JetBlue flyers rather than for baggage/boarding perks.",
    cobranded: true,
  },
  {
    id: "jetblue-plus-card",
    name: "JetBlue Plus Card",
    short: "JetBlue Plus",
    network: "Mastercard",
    issuer: "Barclays",
    color: "#003876",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1X points on all other purchases" },
    categories: [
      { key: "jetblue_paisly", rate: 6, label: "Eligible JetBlue and Paisly purchases", keywords: ["jetblue flight", "book jetblue", "jetblue.com", "paisly", "fly jetblue"] },
      { key: "dining_grocery", rate: 2, label: "Restaurants and eligible grocery stores", keywords: ["restaurant", "dining", "grocery store", "supermarket"] },
    ],
    notes: "Free first checked bag for cardholder and up to 3 companions on JetBlue-operated flights, 10% points back after award redemption, 50% savings on inflight purchases, faster Mosaic status earning, and a $100 JetBlue Vacations credit — the clear pick over the no-fee JetBlue Card for anyone checking bags on JetBlue.",
    cobranded: true,
  },
  {
    id: "alaska-airlines-visa-signature",
    name: "Atmos Rewards Ascent Visa Signature Card (formerly Alaska Airlines Visa Signature Card)",
    short: "Alaska Airlines Visa",
    network: "Visa",
    issuer: "Bank of America",
    color: "#00385e",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1 point per dollar on all other purchases" },
    categories: [
      { key: "alaska_hawaiian_purchases", rate: 3, label: "Eligible Alaska Airlines and Hawaiian Airlines purchases", keywords: ["alaska airlines flight", "hawaiian airlines flight", "book alaska", "alaskaair.com", "fly alaska", "fly hawaiian"] },
      { key: "gas_transit_streaming", rate: 2, label: "Gas, EV charging, cable, streaming services, and local transit (incl. rideshare)", keywords: ["gas station", "fuel", "ev charging", "cable bill", "streaming subscription", "netflix", "uber", "lyft", "local transit"] },
    ],
    notes: "Famous $99 Companion Fare each anniversary (after $6,000 prior-year spend), free checked bag and preferred boarding for cardholder plus up to 6 guests, 20% back on inflight purchases, and $100 off Alaska Lounge+ membership — best for travelers who fly Alaska/Hawaiian with a companion and value the low-fee companion fare over pure point-earning rate.",
    cobranded: true,
  },
  {
    id: "aadvantage-platinum-select-citi",
    name: "Citi / AAdvantage Platinum Select World Elite Mastercard",
    short: "AAdvantage Platinum Select",
    network: "Mastercard",
    issuer: "Citi",
    color: "#0078d2",
    unit: "x",
    pointValue: 1.3,
    base: { rate: 1, label: "1 AAdvantage mile per dollar on all other purchases" },
    categories: [
      { key: "aa_purchases", rate: 2, label: "Eligible American Airlines purchases", keywords: ["american airlines flight", "book american airlines", "aa.com", "fly american"] },
      { key: "restaurants", rate: 2, label: "Restaurants", keywords: ["restaurant", "dining"] },
      { key: "gas_stations", rate: 2, label: "Gas stations", keywords: ["gas station", "fuel"] },
    ],
    notes: "Note: this card was formerly issued by Citi and Barclays in parallel (Barclays 'AAdvantage Aviator'); as of the April 2026 portfolio transfer, Citi is now the exclusive issuer of AAdvantage-branded consumer cards, and legacy Barclays Aviator cardholders have been migrated to Citi equivalents. This mid-tier card offers a free first checked bag for cardholder plus up to 4 companions on domestic itineraries, preferred boarding, 25% inflight savings, and a $125 flight discount after $20,000 annual spend — best for AA flyers wanting solid everyday bonus categories (dining/gas) plus baggage/boarding perks at a moderate fee.",
    cobranded: true,
  },
  {
    id: "marriott-bonvoy-boundless",
    name: "Marriott Bonvoy Boundless Credit Card",
    short: "Marriott Boundless",
    network: "Visa",
    issuer: "Chase",
    color: "#8b3a3a",
    unit: "x",
    pointValue: 0.8,
    base: { rate: 2, label: "All other purchases" },
    categories: [
      { key: "marriott", rate: 6, label: "Marriott Bonvoy hotels", keywords: ["marriott", "bonvoy", "westin", "sheraton", "ritz carlton", "ritz-carlton", "st regis", "st. regis", "w hotel", "w hotels", "courtyard", "residence inn", "fairfield inn", "springhill suites", "towneplace suites", "renaissance hotel", "jw marriott", "ac hotels", "aloft", "element hotels", "moxy hotels", "delta hotels", "gaylord hotels", "le meridien", "four points", "protea hotels", "city express", "design hotels", "edition hotels", "autograph collection", "tribute portfolio"] },
      { key: "grocery-gas-dining", rate: 3, label: "Grocery stores, gas stations, and dining", cap: "$6,000 combined spend per year, then 2X", keywords: ["grocery store", "supermarket", "gas station", "fuel", "restaurant", "dining", "takeout", "food delivery"] },
    ],
    notes: "Best low-fee entry point into Marriott Bonvoy: earns up to 17X total points at Marriott hotels (6X card + Bonvoy membership/status bonuses), gives an annual Free Night Award (up to 35,000 points) and automatic Silver Elite status with 15 Elite Night Credits, making it the pick for casual Marriott stayers who don't want a high annual fee.",
    cobranded: true,
  },
  {
    id: "marriott-bonvoy-brilliant",
    name: "Marriott Bonvoy Brilliant American Express Card",
    short: "Marriott Brilliant",
    network: "Amex",
    issuer: "American Express",
    color: "#5c2323",
    unit: "x",
    pointValue: 0.8,
    base: { rate: 2, label: "All other eligible purchases" },
    categories: [
      { key: "marriott", rate: 6, label: "Marriott Bonvoy hotels", keywords: ["marriott", "bonvoy", "westin", "sheraton", "ritz carlton", "ritz-carlton", "st regis", "st. regis", "w hotel", "w hotels", "courtyard", "residence inn", "fairfield inn", "springhill suites", "towneplace suites", "renaissance hotel", "jw marriott", "ac hotels", "aloft", "element hotels", "moxy hotels", "delta hotels", "gaylord hotels", "le meridien", "four points", "edition hotels", "autograph collection", "tribute portfolio"] },
      { key: "dining", rate: 3, label: "Restaurants worldwide", keywords: ["restaurant", "dining", "takeout", "food delivery", "bar", "cafe"] },
      { key: "flights-direct", rate: 3, label: "Flights booked directly with airlines", keywords: ["airline", "flight booked direct", "airfare"] },
    ],
    notes: "Best for frequent Marriott loyalists who want top-tier perks: automatic Platinum Elite status (50% bonus points on stays, room upgrades), an annual Free Night Award worth up to 85,000 points, 25 Elite Night Credits, $300/year dining credit, and Priority Pass lounge access — the $650 fee is best justified by heavy Marriott stay volume and use of the premium perks.",
    cobranded: true,
  },
  {
    id: "world-of-hyatt",
    name: "World of Hyatt Credit Card",
    short: "World of Hyatt",
    network: "Visa",
    issuer: "Chase",
    color: "#3d1152",
    unit: "x",
    pointValue: 1.6,
    base: { rate: 1, label: "All other purchases" },
    categories: [
      { key: "hyatt", rate: 4, label: "Hyatt hotels and resorts", keywords: ["hyatt", "hyatt regency", "grand hyatt", "park hyatt", "andaz", "hyatt place", "hyatt house", "hyatt centric", "thompson hotels", "alila", "destination hotels", "unbound collection", "mr and mrs smith", "small luxury hotels of the world", "caption by hyatt"] },
      { key: "dining-transit-airfare-gym", rate: 2, label: "Restaurants, airline tickets purchased directly, local transit/commuting, fitness clubs and gym memberships", keywords: ["restaurant", "dining", "cafe", "coffee shop", "airline ticket direct", "taxi", "ride share", "uber", "lyft", "mass transit", "toll", "gym membership", "fitness club"] },
    ],
    notes: "Best value-per-point among hotel cards since Hyatt points are worth roughly double Marriott's and quadruple Hilton's or IHG's; the card gives an annual Category 1-4 Free Night (plus a second after $15,000 spend), automatic Discoverist elite status, and a fast track (5 qualifying nights/year plus 2 more per $5,000 spent) toward higher Hyatt tiers, making it ideal for travelers who prioritize redemption value over broad hotel availability.",
    cobranded: true,
  },
  {
    id: "ihg-one-rewards-premier",
    name: "IHG One Rewards Premier Credit Card",
    short: "IHG Premier",
    network: "Visa",
    issuer: "Chase",
    color: "#c8102e",
    unit: "x",
    pointValue: 0.55,
    base: { rate: 3, label: "All other purchases" },
    categories: [
      { key: "ihg", rate: 10, label: "IHG Hotels & Resorts", keywords: ["ihg", "holiday inn", "holiday inn express", "intercontinental", "crowne plaza", "candlewood suites", "staybridge suites", "kimpton", "hotel indigo", "even hotels", "avid hotels", "atwell suites", "voco", "regent hotels", "six senses", "vignette collection", "iberostar"] },
      { key: "travel-dining-gas", rate: 5, label: "Travel, dining, and gas stations", keywords: ["travel", "airfare", "hotel booking", "restaurant", "dining", "gas station", "fuel"] },
    ],
    notes: "Best for frequent IHG guests seeking elite perks without a huge fee: earns up to 26X total points at IHG properties (10X card + up to 16X membership/status), grants automatic Platinum Elite status, an Anniversary Free Night (up to 40,000-point value), and a 4th-night-free benefit on reward stays, plus a $100 statement credit and 10,000 bonus points each year $20,000 is spent.",
    cobranded: true,
  },
  {
    id: "ihg-one-rewards-traveler",
    name: "IHG One Rewards Traveler Credit Card",
    short: "IHG Traveler",
    network: "Visa",
    issuer: "Chase",
    color: "#e2231a",
    unit: "x",
    pointValue: 0.55,
    base: { rate: 2, label: "All other purchases" },
    categories: [
      { key: "ihg", rate: 5, label: "IHG Hotels & Resorts", keywords: ["ihg", "holiday inn", "holiday inn express", "intercontinental", "crowne plaza", "candlewood suites", "staybridge suites", "kimpton", "hotel indigo", "even hotels", "avid hotels", "atwell suites", "voco", "regent hotels", "six senses", "vignette collection"] },
      { key: "dining-utilities-streaming-gas", rate: 3, label: "Dining, utilities, select streaming services, and gas stations", keywords: ["restaurant", "dining", "utility bill", "streaming service", "gas station", "fuel"] },
    ],
    notes: "Best no-annual-fee option for occasional IHG stayers: earns up to 17X total points at IHG hotels (5X card + up to 12X membership/Silver status), includes automatic Silver Elite status, the 4th-night-free redemption perk, and a path to Gold Elite status after $20,000 annual spend — a strong choice for those unwilling to pay a fee purely for hotel perks.",
    cobranded: true,
  },
  {
    id: "hilton-honors-amex",
    name: "Hilton Honors American Express Card",
    short: "Hilton Honors",
    network: "Amex",
    issuer: "American Express",
    color: "#6a3fa0",
    unit: "x",
    pointValue: 0.45,
    base: { rate: 3, label: "All other eligible purchases" },
    categories: [
      { key: "hilton", rate: 7, label: "Hotels & Resorts within the Hilton portfolio", keywords: ["hilton", "hampton inn", "hilton garden inn", "doubletree", "embassy suites", "homewood suites", "home2 suites", "tru by hilton", "canopy by hilton", "curio collection", "tapestry collection", "waldorf astoria", "conrad hotels", "motto by hilton", "signia by hilton", "lxr hotels", "spark by hilton"] },
      { key: "dining", rate: 5, label: "U.S. restaurants (including takeout and delivery)", keywords: ["restaurant", "dining", "takeout", "food delivery"] },
      { key: "groceries", rate: 5, label: "U.S. supermarkets", keywords: ["supermarket", "grocery store"] },
      { key: "gas", rate: 5, label: "U.S. gas stations", keywords: ["gas station", "fuel"] },
    ],
    notes: "Best no-annual-fee entry into Hilton Honors for those who want strong everyday bonus categories (dining, groceries, gas at 5X) with zero cost; includes automatic Hilton Honors Silver status but no free night certificate, making it a complement to the premium no-fee-comparison Aspire card rather than a replacement.",
    cobranded: true,
  },
  {
    id: "hilton-honors-amex-surpass",
    name: "Hilton Honors American Express Surpass Card",
    short: "Hilton Surpass",
    network: "Amex",
    issuer: "American Express",
    color: "#4b2c78",
    unit: "x",
    pointValue: 0.45,
    base: { rate: 3, label: "All other eligible purchases" },
    categories: [
      { key: "hilton", rate: 12, label: "Hotels & Resorts within the Hilton portfolio", keywords: ["hilton", "hampton inn", "hilton garden inn", "doubletree", "embassy suites", "homewood suites", "home2 suites", "tru by hilton", "canopy by hilton", "curio collection", "tapestry collection", "waldorf astoria", "conrad hotels", "motto by hilton", "signia by hilton", "lxr hotels", "spark by hilton"] },
      { key: "dining", rate: 6, label: "U.S. restaurants (including takeout and delivery)", keywords: ["restaurant", "dining", "takeout", "food delivery"] },
      { key: "groceries", rate: 6, label: "U.S. supermarkets", keywords: ["supermarket", "grocery store"] },
      { key: "gas", rate: 6, label: "U.S. gas stations", keywords: ["gas station", "fuel"] },
      { key: "online-retail", rate: 4, label: "U.S. online retail purchases", keywords: ["online retail", "online shopping", "e-commerce purchase"] },
    ],
    notes: "Sits between the no-fee Hilton Honors card and the Aspire: automatic Hilton Honors Gold status (5th night free on award stays, space-available room upgrades, executive lounge access at many properties), a Free Night Reward after $15,000 annual spend, and a path to Diamond status after $40,000 spend — best for mid-frequency Hilton travelers who want Gold-level perks without the Aspire's $550+ fee.",
    cobranded: true,
  },
  {
    id: "prime-visa",
    name: "Prime Visa",
    short: "Prime Visa",
    network: "Visa",
    issuer: "Chase (Amazon)",
    color: "#ff9900",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1, label: "All other purchases" },
    categories: [
      { key: "amazon_prime", rate: 5, label: "Amazon.com, Audible.com, Whole Foods Market, and Chase Travel (with eligible Prime membership)", keywords: ["amazon", "amazon.com", "audible", "whole foods", "whole foods market", "chase travel", "amazon prime"] },
      { key: "amazon_non_prime", rate: 3, label: "Amazon.com, Audible.com, and Whole Foods Market without Prime membership (card auto-converts to Amazon Visa terms)", keywords: ["amazon", "amazon.com", "audible", "whole foods", "whole foods market"] },
      { key: "gas_dining_transit", rate: 2, label: "Gas stations, restaurants, and local transit/commuting (including rideshare)", keywords: ["gas station", "gasoline", "fuel", "restaurant", "dining", "local transit", "commuting", "rideshare", "uber", "lyft", "subway fare", "bus fare"] },
    ],
    notes: "Best pick for Amazon Prime members who shop heavily at Amazon.com and Whole Foods; the 5% rate requires an active, eligible Prime membership ($139/yr or $14.99/mo) — without it the card converts to the Amazon Visa's 3% Amazon rate. No annual fee beyond Prime membership cost.",
    cobranded: true,
  },
  {
    id: "amazon-visa",
    name: "Amazon Visa",
    short: "Amazon Visa",
    network: "Visa",
    issuer: "Chase (Amazon)",
    color: "#ff9900",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1, label: "All other purchases" },
    categories: [
      { key: "amazon", rate: 3, label: "Amazon.com, Amazon Fresh, Whole Foods Market, and Chase Travel purchases", keywords: ["amazon", "amazon.com", "amazon fresh", "whole foods", "whole foods market", "chase travel"] },
      { key: "gas_dining_transit", rate: 2, label: "Gas stations, restaurants, and local transit/commuting (including rideshare)", keywords: ["gas station", "gasoline", "fuel", "restaurant", "dining", "local transit", "commuting", "rideshare", "uber", "lyft"] },
    ],
    notes: "Still actively offered as of 2026 for non-Prime members — gives 3% back at Amazon/Whole Foods without requiring a Prime membership; best pick for occasional Amazon shoppers who don't want to pay for Prime. No annual fee.",
    cobranded: true,
  },
  {
    id: "costco-anywhere-visa-citi",
    name: "Costco Anywhere Visa Card by Citi",
    short: "Costco Anywhere Visa",
    network: "Visa",
    issuer: "Citi (Costco)",
    color: "#e01a2b",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1, label: "All other purchases" },
    categories: [
      { key: "gas_costco", rate: 5, label: "Gas at Costco", cap: "Combined with other eligible gas/EV charging at $7,000 spend per year, then 1%", keywords: ["costco gas", "costco gas station", "costco fuel"] },
      { key: "gas_other", rate: 4, label: "Other eligible gas and EV charging", cap: "Combined with Costco gas at $7,000 spend per year, then 1%", keywords: ["gas station", "gasoline", "fuel", "ev charging", "electric vehicle charging"] },
      { key: "dining_travel", rate: 3, label: "Restaurants and eligible travel, including Costco Travel", keywords: ["restaurant", "dining", "travel", "airfare", "hotel", "car rental", "cruise", "costco travel"] },
      { key: "costco_purchases", rate: 2, label: "Costco and Costco.com purchases", keywords: ["costco", "costco warehouse", "costco.com"] },
    ],
    notes: "Best pick for Costco members who drive a lot — 5% on Costco gas and 4% on other gas/EV charging (up to $7,000 combined spend/year) makes it a top gas card. Requires a paid Costco membership to apply and keep the card; rewards are paid once annually in February as a certificate redeemable only at U.S. Costco warehouses.",
    cobranded: true,
  },
  {
    id: "bjs-one-mastercard",
    name: "BJ's One Credit Card",
    short: "BJ's One",
    network: "Mastercard",
    issuer: "Capital One (BJ's)",
    color: "#c8102e",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1.5, label: "Purchases made outside of BJ's" },
    categories: [
      { key: "bjs_purchases", rate: 3, label: "Eligible purchases at BJ's (in-club, BJs.com, or the BJ's app)", keywords: ["bj's", "bjs wholesale", "bjs.com", "bj's wholesale club"] },
    ],
    notes: "No annual fee (requires a paid BJ's membership). Rewards never expire and redeem in-club, on BJs.com, or in the BJ's app once you hit a $10 minimum balance. BJ's Gas purchases don't earn rewards but do get an instant 10\u00a2/gallon discount when paid with this card and membership scanned.",
    cobranded: true,
  },
  {
    id: "bjs-one-plus-mastercard",
    name: "BJ's One+ Credit Card",
    short: "BJ's One+",
    network: "Mastercard",
    issuer: "Capital One (BJ's)",
    color: "#8c0c22",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 2, label: "Purchases made outside of BJ's" },
    categories: [
      { key: "bjs_purchases", rate: 5, label: "Eligible purchases at BJ's (in-club, BJs.com, or the BJ's app)", keywords: ["bj's", "bjs wholesale", "bjs.com", "bj's wholesale club"] },
    ],
    notes: "Requires a paid BJ's Perks Elite membership (higher tier than the base BJ's One card). $0 card annual fee on top of that membership. Top rate on BJ's purchases (5%) and the best outside-BJ's rate (2%) of the two BJ's cards. BJ's Gas purchases don't earn rewards but do get an instant 15\u00a2/gallon discount when paid with this card and membership scanned.",
    cobranded: true,
  },
  {
    id: "target-circle-card-mastercard",
    name: "Target Circle Card (Mastercard)",
    short: "Target Circle Card",
    network: "Mastercard",
    issuer: "TD Bank (Target)",
    color: "#cc0000",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1, label: "All other purchases outside Target (earned as Target GiftCard credit)" },
    categories: [
      { key: "target", rate: 5, label: "Target and Target.com purchases (instant discount)", keywords: ["target", "target.com", "target store", "target circle", "target pickup", "target drive up", "shipt"] },
      { key: "dining_gas", rate: 2, label: "Dining and gas stations (Mastercard version only, earned as Target GiftCard)", keywords: ["restaurant", "dining", "gas station", "gasoline", "fuel"] },
    ],
    notes: "Best pick for frequent Target shoppers — the 5% discount applies instantly at checkout in-store and online, no points to track. Three variants exist: the store-only Target Circle Credit Card (5% at Target only, easier approval), the Target Circle Mastercard (adds 2% dining/gas and 1% elsewhere but requires excellent credit ~750+, rewards outside Target are Target GiftCard credits not cash), and a debit/reloadable version. Excludes pharmacy, Target Optical, and gift card purchases from the 5% discount.",
    cobranded: true,
  },
  {
    id: "paypal-cashback-mastercard",
    name: "PayPal Cashback Mastercard",
    short: "PayPal Cashback",
    network: "Mastercard",
    issuer: "Synchrony (PayPal)",
    color: "#003087",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1.5, label: "All other purchases everywhere Mastercard is accepted" },
    categories: [
      { key: "paypal_checkout", rate: 3, label: "Purchases checked out through PayPal", keywords: ["paypal", "paypal checkout", "pay with paypal", "ebay via paypal"] },
    ],
    notes: "Best pick for people who regularly pay with PayPal Checkout online — unlimited 3% back with no rotating categories or spending caps, plus a strong 1.5% base rate on everything else. No annual fee; requires an open, linked PayPal account in good standing to earn rewards. Note the rate dropped from a historical 2% flat rate to the current 1.5%/3% structure.",
    cobranded: true,
  },
  {
    id: "my-best-buy-visa-citi",
    name: "My Best Buy Visa Card",
    short: "My Best Buy Visa",
    network: "Visa",
    issuer: "Citi (Best Buy)",
    color: "#0046be",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1, label: "All other purchases" },
    categories: [
      { key: "bestbuy", rate: 5, label: "Best Buy purchases (5% back in rewards, or $5 reward certificate per $100 spent; choose rewards or 0% financing)", keywords: ["best buy", "bestbuy.com", "best buy store"] },
      { key: "gas", rate: 3, label: "Gas purchases", keywords: ["gas station", "gasoline", "fuel"] },
      { key: "grocery_dining", rate: 2, label: "Grocery, dining, and takeout purchases", keywords: ["grocery", "supermarket", "restaurant", "dining", "takeout", "food delivery"] },
    ],
    notes: "Best pick for shoppers who buy electronics at Best Buy and want rewards usable beyond the store — the My Best Buy Visa earns 5% at Best Buy plus 3% gas and 2% grocery/dining/takeout anywhere Visa is accepted. A separate store-only My Best Buy Credit Card offers the same 5% at Best Buy (or promotional financing) but cannot be used elsewhere. Annual fee varies by creditworthiness (issuer states a range, typically $0).",
    cobranded: true,
  },
  {
    id: "sams-club-mastercard",
    name: "Sam's Club Mastercard",
    short: "Sam's Club Mastercard",
    network: "Mastercard",
    issuer: "Synchrony (Sam's Club)",
    color: "#0067a0",
    unit: "%",
    pointValue: 1.0,
    base: { rate: 1, label: "Other purchases (Sam's Cash)" },
    categories: [
      { key: "gas", rate: 5, label: "Gas anywhere Mastercard is accepted", cap: "First $6,000 spend per year, then 1%", keywords: ["gas station", "gasoline", "fuel"] },
      { key: "sams_club", rate: 3, label: "Sam's Club purchases (Plus members earn 3%; Club members earn 1%)", keywords: ["sam's club", "sams club", "samsclub.com"] },
      { key: "dining", rate: 3, label: "Dining and takeout", keywords: ["restaurant", "dining", "takeout", "food delivery"] },
    ],
    notes: "Best pick for Sam's Club Plus members who also drive a lot — 5% on gas (up to $6,000/year) is among the highest gas rates of any retail card, plus 3% at Sam's Club for Plus members (vs. only 1% for base Club members). Rewards (Sam's Cash) are capped at $5,000 earned per calendar year and are redeemable only at Sam's Club or SamsClub.com. No annual fee.",
    cobranded: true,
  },
  {
    id: "gap-good-rewards-mastercard",
    name: "Gap Good Rewards Mastercard",
    short: "Gap Good Rewards",
    network: "Mastercard",
    issuer: "Barclays (Gap Inc.)",
    color: "#002649",
    unit: "x",
    pointValue: 0.01,
    base: { rate: 1, label: "All other purchases anywhere Mastercard is accepted (1 point per $1)" },
    categories: [
      { key: "gap_family_brands", rate: 5, label: "Purchases at Gap, Old Navy, Banana Republic, and Athleta", keywords: ["gap", "old navy", "banana republic", "athleta", "gap inc"] },
    ],
    notes: "Best pick for loyal shoppers of the Gap family of brands (Gap, Old Navy, Banana Republic, Athleta) — 5 points per $1 (5% equivalent value) at those stores, with points worth 1 cent each (100 points = $1) redeemable only at Gap Inc. brands. Issued by Barclays Bank Delaware (moved from Synchrony in 2022); no annual fee. A store-only version (Gap Good Rewards Credit Card) is also available, limited to Gap Inc. brands only. Best avoided by shoppers who don't frequent these retailers, since 1x elsewhere is weak and rewards aren't broadly redeemable. Note: the program is mid-rebrand to 'Encore' as of 2026, with some reports of a 3x eligible-apparel-elsewhere category being added — verify current terms before applying.",
    cobranded: true,
  },
];

CARD_CATALOG.push(...COBRAND_CARDS);

// Deep clone helper
function cloneDefaults() {
  const starters = CARD_CATALOG.filter((c) => STARTER_CARD_IDS.includes(c.id));
  return JSON.parse(JSON.stringify(starters));
}

function cloneCatalog() {
  return JSON.parse(JSON.stringify(CARD_CATALOG));
}
